export default {
  error: {
    samePassword: 'The password for verification is different.',
    parsingJSON: 'There was an error parsing JSON.',
    emptyContent: 'This {0} is empty.',
    keywordMinlength: 'You can enter a search term of {0} or more characters.',
  },
  confirm: {
    deleteItem: 'Are you sure you want to delete this {0}?',
    logout: 'Do you really want to log out?',
    deleteFiles: 'Are you sure you want to delete {0} files?',
    deleteFileItems: 'Are you sure you want to delete {0} items?',
    deleteFile: `Are you sure you want to delete this item?\nIf you delete this data, it cannot be recovered.`,
    resetToken: 'Reset token data?',
    reload: 'A value that requires a refresh has changed.\nShould I refresh now?',
  },
  success: {
    get: 'You got a {0}.',
    create: 'Create a {0}.',
    edit: 'Edit a {0}.',
    delete: 'Delete a {0}',
    change: 'Change a {0}',
    draftSave: 'Temporary save completed.',
    resetTokens: 'Token reset.',
  },
  fail: {
    get: 'Failed to get {0}.',
    create: 'Failed to create {0}.',
    edit: 'Failed to edit {0}.',
    delete: 'Failed to delete {0}.',
    change: 'Failed to change {0}.',
    draftSave: 'Temporary save failed.',
    checkOrderDate: '"OrderDate" check failed.',
    resetTokens: 'Token reset failed.',
  },
  word: {
    apply: 'Apply',
    user: 'User',
    app: 'App',
    nest: 'Nest',
    password: 'Password',
    add: 'Add',
    edit: 'Edit',
    category: 'Category',
    order: 'Order',
    content: 'Content',
    article: 'Article',
    comment: 'Comment',
    file: 'File',
    checklist: 'Checklist',
    json: 'JSON',
    board: 'Board',
    preference: 'Preference',
    language: 'Language',
    theme: 'Theme',
  },
  words: {
    warningDeleteItem: 'If this {0} is deleted, it cannot be recovered.',
    guideCurrentPassword: 'Please enter the password you are using.',
    guideNewPassword: 'Please enter a new password.',
    guideVerifyPassword: 'Please enter the same password as your new password.',
    guideSamePassword: 'The current password and the new password are the same.',
    pleaseCheck: 'Please check {0}.',
    unknownError: 'An unknown error has occurred.',
    deleteApp: 'If you delete this app, all subordinate "nest", "article", "category" and "attachment files" data will be deleted.',
    deleteNest: 'If you delete this nest, all subordinate "article", "category", and "attachment files" data will be deleted.',
    deleteArticle: 'If you delete this article, the associated attachments and comments will be deleted and cannot be recovered.',
    deleteItem: 'element being deleted',
  },
}
