export default {
  error: {
    samePassword: 'The password for verification is different.',
    parsingJSON: 'There was an error parsing JSON.',
    emptyContent: 'This {0} is empty.',
    keywordMinlength: 'You can enter a search term of {0} or more characters.',
  },
  confirm: {
    deleteItem: 'Are you sure you want to delete this {0}?',
    logout: 'Do you really want to log out?',
    deleteFiles: 'Are you sure you want to delete {0} files?',
    deleteFileItems: 'Are you sure you want to delete {0} items?',
    deleteFile: `Are you sure you want to delete this item?\nIf you delete this data, it cannot be recovered.`,
    resetToken: 'Reset token data?',
    reload: 'A value that requires a refresh has changed.\nShould I refresh now?',
  },
  success: {
    get: 'You got a {0}.',
    create: 'Create a {0}.',
    edit: 'Edit a {0}.',
    delete: 'Delete a {0}',
    change: 'Change a {0}',
    draftSave: 'Temporary save completed.',
    resetTokens: 'Token reset.',
  },
  fail: {
    get: 'Failed to get {0}.',
    create: 'Failed to create {0}.',
    edit: 'Failed to edit {0}.',
    delete: 'Failed to delete {0}.',
    change: 'Failed to change {0}.',
    draftSave: 'Temporary save failed.',
    checkOrderDate: '"OrderDate" check failed.',
    resetTokens: 'Token reset failed.',
  },
  word: {
    srl: 'srl',
    apply: 'Apply',
    user: 'User',
    app: 'App',
    appSrl: 'App srl',
    nest: 'Nest',
    nests: 'Nests',
    password: 'Password',
    add: 'Add',
    edit: 'Edit',
    edit2: 'Edit',
    delete: 'Delete',
    category: 'Category',
    categoryName: 'Category Name',
    categories: 'Categories',
    order: 'Order',
    content: 'Content',
    article: 'Article',
    comment: 'Comment',
    file: 'File',
    checklist: 'Checklist',
    json: 'JSON',
    board: 'Board',
    preference: 'Preference',
    language: 'Language',
    theme: 'Theme',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    id: 'ID',
    name: 'Name',
    date: 'Date',
    description: 'Description',
    back: 'Back',
    attachmentFiles: 'Attachment files',
    isCreate: 'Create {0}',
    isEdit: 'Edit {0}',
    isDelete: 'Delete {0}',
    account: 'Account',
    clearTokens: 'Clear tokens',
    logout: 'Logout',
    list: 'List',
    'public': 'Public',
    'private': 'Private',
    hit: 'Hit',
    like: 'Like',
    createNest: 'Create Nest',
    editNest: 'Edit Nest',
    regdate: 'Regdate',
    path: 'Path',
    total: 'Total',
    type: 'Type',
    sort: 'Sort',
    keyword: 'Keyword',
    reset: 'Reset',
    updateFilter: 'Update filter',
    all: 'All',
    card: 'Card',
    thumbnail: 'Thumbnail',
    brick: 'Brick',
    changeNest: 'Change Nest',
    writeComment: 'Write comment',
    create: 'Create',
    cancel: 'Cancel',
    basicFields: 'Basic fields',
    extraFields: 'Extra fields',
    usingCategory: 'Using Category',
    usingComment: 'Using Comment',
    thumbnailSize: 'Thumbnail size',
    thumbnailType: 'Thumbnail type',
    uploadFilesCount: 'Upload files count',
    uploadFilesSize: 'Upload files size',
    alphanumeric: 'Alphanumeric characters',
    width: 'Width',
    height: 'Height',
    crop: 'Crop',
    resize: 'Resize',
    close: 'Close',
  },
  words: {
    warningDeleteItem: 'If this {0} is deleted, it cannot be recovered.',
    guideCurrentPassword: 'Please enter the password you are using.',
    guideNewPassword: 'Please enter a new password.',
    guideVerifyPassword: 'Please enter the same password as your new password.',
    guideSamePassword: 'The current password and the new password are the same.',
    pleaseCheck: 'Please check {0}.',
    pleaseInput: 'Please input {0}.',
    pleaseInputOnly: 'Please enter only {0}.',
    unknownError: 'An unknown error has occurred.',
    deleteApp: 'If you delete this app, all subordinate "nest", "article", "category" and "attachment files" data will be deleted.',
    deleteNest: 'If you delete this nest, all subordinate "article", "category", and "attachment files" data will be deleted.',
    deleteArticle: 'If you delete this article, the associated attachments and comments will be deleted and cannot be recovered.',
    deleteItem: 'element being deleted.',
    selectCategory: 'Please select category.',
    descriptionOf: 'Description of the {0}.',
    noItem: 'No Item.',
    processing: 'Processing..',
    selectAppSrl: 'Select app-srl',
    inputDescription: 'Input a description for this "{0}".',
    uploadFilesCount: 'Set the number of files that can be uploaded.',
  },
  header: {
    description: {
      app: 'This module manages nests by grouping them. It is recommended to use it as the project name.',
      article: 'This module manages posted articles.',
      categories: 'This module manages the classification of `Articles`.',
      nests: 'This module manages nests.',
      users: 'This module manages the list of users.',
      json: 'This module manages `JSON` data.',
      files: 'This module manages attached files.',
      checklist: 'This module manages checklists.',
      preference: 'Manage configuration values.',
      guide: 'This page collects components and tools for development.',
    },
    uploadFilesUrl: 'Upload files by URL',
  },
  monthNames: [ 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December' ],
  weekNames: [ 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday' ],
  weekShortNames: [ 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat' ],
}
