export default {
  error: {
    samePassword: '확인용 비밀번호가 다릅니다.',
    parsingJSON: 'JSON 파싱하는데 오류가 발생헀습니다.',
    emptyContent: '이 {0}은 비어있습니다.',
  },
  confirm: {
    deleteItem: '이 {0}을(를) 삭제할까요?',
    logout: '정말 로그아웃 할까요?',
  },
  success: {
    get: '{0}을(를) 가져왔습니다.',
    create: '{0}을(를) 만들었습니다.',
    edit: '{0}을(를) 수정했습니다.',
    delete: '{0}을(를) 삭제했습니다.',
    change: '{0}을(를) 변경했습니다.',
    draftSave: '임시저장했습니다.',
  },
  fail: {
    get: '{0}을(를) 가져오지 못했습니다.',
    create: '{0}을(를) 만들지 못했습니다.',
    edit: '{0}을(를) 수정하지 못했습니다.',
    delete: '{0}을(를) 삭제하지 못했습니다.',
    change: '{0}을(를) 변경하지 못했습니다.',
    draftSave: '임시저장하지 못했습니다.',
    checkOrderDate: 'OrderDate 검사 실패했습니다.',
  },
  word: {
    user: '사용자',
    app: '앱',
    nest: '둥지',
    password: '비밀번호',
    add: '추가',
    edit: '수정',
    category: '분류',
    order: '순서',
    content: '내용',
    article: '아티클',
  },
  words: {
    warningDeleteItem: '이 {0}을(를) 삭제하면 복구할 수 없습니다.',
    guideCurrentPassword: '사용하고 있는 비밀번호를 입력해주세요.',
    guideNewPassword: '새로운 비밀번호를 입력해주세요.',
    guideVerifyPassword: '새로운 비밀번호와 같은 비밀번호를 입력해주세요.',
    guideSamePassword: '현재 비밀번호와 새로운 비밀번호가 같습니다.',
    successChangePassword: '비밀번호가 변경되었습니다.',
    pleaseCheck: '{0}을(를) 확인해주세요.',
    unknownError: '알 수 없는 오류가 발생했습니다.',
  },
}
