export default {
  error: {
    samePassword: '확인용 비밀번호가 다릅니다.',
    parsingJSON: 'JSON 파싱하는데 오류가 발생했습니다.',
    emptyContent: '이 {0}은 비어있습니다.',
    keywordMinlength: '검색어를 {0}자이상 입력할 수 있습니다.',
  },
  confirm: {
    deleteItem: '이 {0}을(를) 삭제할까요?',
    logout: '정말 로그아웃 할까요?',
    deleteFiles: '정말 {0}개의 파일을 삭제할까요?',
    deleteFileItems: '정말 {0}개의 항목들을 삭제할까요?',
    deleteFile: `이 항목을 삭제할까요?\n이 데이터를 삭제하면 복구할 수 없습니다.`,
    resetToken: '토큰 데이터들을 리셋할까요?',
    reload: '새로고침이 필요한 값이 변경되었습니다.\n지금 새로고침 할까요?',
  },
  success: {
    get: '{0}을(를) 가져왔습니다.',
    create: '{0}을(를) 만들었습니다.',
    edit: '{0}을(를) 수정했습니다.',
    delete: '{0}을(를) 삭제했습니다.',
    change: '{0}을(를) 변경했습니다.',
    draftSave: '임시저장했습니다.',
    resetTokens: '토큰을 재설정했습니다.',
  },
  fail: {
    get: '{0}을(를) 가져오지 못했습니다.',
    create: '{0}을(를) 만들지 못했습니다.',
    edit: '{0}을(를) 수정하지 못했습니다.',
    delete: '{0}을(를) 삭제하지 못했습니다.',
    change: '{0}을(를) 변경하지 못했습니다.',
    draftSave: '임시저장하지 못했습니다.',
    checkOrderDate: 'OrderDate 검사 실패했습니다.',
    resetTokens: '토큰 재설정에 실패했습니다.',
  },
  word: {
    apply: '적용하기',
    user: '사용자',
    app: '앱',
    nest: '둥지',
    password: '비밀번호',
    add: '추가',
    edit: '수정',
    edit2: '수정하기',
    delete: '삭제',
    isDelete: '{0} 삭제하기',
    category: '분류',
    categories: '분류',
    order: '순서',
    content: '내용',
    article: '아티클',
    comment: '댓글',
    file: '첨부파일',
    checklist: '체크리스트',
    json: 'JSON',
    board: '보드',
    preference: '환경설정',
    language: '언어',
    theme: '테마',
    system: '시스템',
    light: '라이트',
    dark: '다크',
    id: '아이디',
    name: '이름',
    description: '설명',
    back: '뒤로가기',
    attachmentFiles: '첨부파일',
    isCreate: '{0} 만들기',
    account: '계정',
    clearTokens: '토큰 정리하기',
    logout: '로그아웃',
  },
  words: {
    warningDeleteItem: '이 {0}을(를) 삭제하면 복구할 수 없습니다.',
    guideCurrentPassword: '사용하고 있는 비밀번호를 입력해주세요.',
    guideNewPassword: '새로운 비밀번호를 입력해주세요.',
    guideVerifyPassword: '새로운 비밀번호와 같은 비밀번호를 입력해주세요.',
    guideSamePassword: '현재 비밀번호와 새로운 비밀번호가 같습니다.',
    pleaseCheck: '{0}을(를) 확인해주세요.',
    unknownError: '알 수 없는 오류가 발생했습니다.',
    deleteApp: '이 앱을 삭제하면 하위의 "둥지", "아티클", "분류", "첨부파일" 데이터들이 전부 삭제됩니다.',
    deleteNest: '이 둥지를 삭제하면 하위의 "아티클", "분류", "첨부파일" 데이터들이 전부 삭제됩니다.',
    deleteArticle: '이 아티클을 삭제하면 관련된 첨부파일, 댓글들을 삭제하며 복구할 수 없습니다.',
    deleteItem: '삭제되는 요소',
    selectCategory: '분류를 선택해주세요.',
  },
}
