import * as lucide from 'lucide-vue-next'

const icons = {
  'box': lucide.Box,
  'book': lucide.Book,
  'bubbles': lucide.Bubbles,
  'bird': lucide.Bird,
  'between-horizontal-start': lucide.BetweenHorizontalStart,
  'brush-cleaning': lucide.BrushCleaning,
  'book-open': lucide.BookOpen,
  'ban': lucide.Ban,
  'bug': lucide.Bug,
  'chevron-down': lucide.ChevronDown,
  'chevron-up': lucide.ChevronUp,
  'chevron-left': lucide.ChevronLeft,
  'chevrons-left': lucide.ChevronsLeft,
  'chevron-right': lucide.ChevronRight,
  'chevrons-right': lucide.ChevronsRight,
  'cloud': lucide.Cloud,
  'cloud-check': lucide.CloudCheck,
  'code': lucide.Code,
  'code-xml': lucide.CodeXml,
  'check': lucide.Check,
  'check-square': lucide.CheckSquare,
  'circle-slash': lucide.CircleSlash,
  'circle-plus': lucide.CirclePlus,
  'crop': lucide.Crop,
  'droplet': lucide.Droplet,
  'download': lucide.Download,
  'edit': lucide.Edit,
  'external-link': lucide.ExternalLink,
  'ellipsis': lucide.Ellipsis,
  'eye': lucide.Eye,
  'file': lucide.File,
  'file-search': lucide.FileSearch,
  'file-code-2': lucide.FileCode2,
  'file-image': lucide.FileImage,
  'file-down': lucide.FileDown,
  'file-text': lucide.FileText,
  'folder': lucide.Folder,
  'folder-git-2': lucide.FolderGit2,
  'grid': lucide.Grid,
  'hash': lucide.Hash,
  'image': lucide.Image,
  'images': lucide.Images,
  'log-out': lucide.LogOut,
  'link': lucide.Link,
  'list': lucide.List,
  'loader': lucide.Loader,
  'layout-grid': lucide.LayoutGrid,
  'lock': lucide.Lock,
  'lock-keyhole-open': lucide.LockKeyholeOpen,
  'arrow-left': lucide.ArrowLeft,
  'archive': lucide.Archive,
  'menu': lucide.Menu,
  'more-horizontal': lucide.MoreHorizontal,
  'minimize-2': lucide.Minimize2,
  'move': lucide.Move,
  'moon': lucide.Moon,
  'power': lucide.Power,
  'power-off': lucide.PowerOff,
  'package': lucide.Package,
  'plus': lucide.Plus,
  'paperclip': lucide.Paperclip,
  'plug': lucide.Plug,
  'plug-zap': lucide.PlugZap,
  'rotate-ccw': lucide.RotateCcw,
  'star': lucide.Star,
  'sun': lucide.Sun,
  'settings': lucide.Settings,
  'server': lucide.Server,
  'search': lucide.Search,
  'scan-search': lucide.ScanSearch,
  'square': lucide.Square,
  'square-check-big': lucide.SquareCheckBig,
  'square-minus': lucide.SquareMinus,
  'square-plus': lucide.SquarePlus,
  'space': lucide.Space,
  'trash-2': lucide.Trash2,
  'tag': lucide.Tag,
  'tv': lucide.Tv,
  'user': lucide.User,
  'upload': lucide.Upload,
  'unplug': lucide.Unplug,
  'workflow': lucide.Workflow,
  'x-circle': lucide.XCircle,
  'x': lucide.X,
  'zoom-in': lucide.ZoomIn,
  'zoom-out': lucide.ZoomOut,
}

export function iconRandomPick()
{
  const iconNames = Object.keys(icons)
  return iconNames[Math.floor(Math.random() * iconNames.length)]
}

export default icons
